skip_commits:
  message: /^Merge pull request /

environment:
  PYTHONIOENCODING: "UTF-8"

  matrix:
    - PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"
      CONDA_PY: "35"
      CONDA_INSTALL_LOCN: "C:\\Miniconda35-x64"
    - PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
      CONDA_PY: "36"
      CONDA_INSTALL_LOCN: "C:\\Miniconda36-x64"
    - PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "64"
      CONDA_PY: "37"
      CONDA_INSTALL_LOCN: "C:\\Miniconda37-x64"

install:
    # Use the pre-installed Miniconda for the desired arch
    - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
    - cmd: conda update -y -q conda
    - cmd: conda install -y -q -c defaults -c conda-forge -c cmutel numpy-base asteval astunparse stats_arrays pytest
    - cmd: cd
    - cmd: pip install -e .

build: false

test_script:
  - "pytest -v"
